Class {
	#name : 'DragonTestObjectNoDefinitionSubclass',
	#superclass : 'DragonTestObjectNoDefinition',
	#instVars : [
		'subclassSlot'
	],
	#category : 'Dragon-Tests',
	#package : 'Dragon',
	#tag : 'Tests'
}

{ #category : 'accessing' }
DragonTestObjectNoDefinitionSubclass >> subclassSlot [

	^ subclassSlot
]

{ #category : 'accessing' }
DragonTestObjectNoDefinitionSubclass >> subclassSlot: anObject [

	subclassSlot := anObject
]
