Class {
	#name : 'DragonTestObjectNoDefinitionSubclassSublClass',
	#superclass : 'DragonTestObjectNoDefinitionSubclass',
	#instVars : [
		'subClassSubclassSlot'
	],
	#category : 'Dragon',
	#package : 'Dragon'
}

{ #category : 'accessing' }
DragonTestObjectNoDefinitionSubclassSublClass >> subClassSubclassSlot [

	^ subClassSubclassSlot
]

{ #category : 'accessing' }
DragonTestObjectNoDefinitionSubclassSublClass >> subClassSubclassSlot: anObject [

	subClassSubclassSlot := anObject
]
