Class {
	#name : 'DragonNoVerboseLevel',
	#superclass : 'Object',
	#category : 'Dragon-Model',
	#package : 'Dragon',
	#tag : 'Model'
}

{ #category : 'as yet unclassified' }
DragonNoVerboseLevel >> endBuilding [
]

{ #category : 'as yet unclassified' }
DragonNoVerboseLevel >> endClass: aClass [
]

{ #category : 'as yet unclassified' }
DragonNoVerboseLevel >> startBuilding: aCollection [
]

{ #category : 'as yet unclassified' }
DragonNoVerboseLevel >> startClass: aClass [
]
