Class {
	#name : 'DragonConstructorDescription',
	#superclass : 'Object',
	#instVars : [
		'constructorArguments',
		'constructorValuable'
	],
	#category : 'Dragon-Model',
	#package : 'Dragon',
	#tag : 'Model'
}

{ #category : 'accessing' }
DragonConstructorDescription >> constructorArguments [

	^ constructorArguments
]

{ #category : 'accessing' }
DragonConstructorDescription >> constructorArguments: anObject [

	constructorArguments := anObject
]

{ #category : 'accessing' }
DragonConstructorDescription >> constructorValuable [

	^ constructorValuable
]

{ #category : 'accessing' }
DragonConstructorDescription >> constructorValuable: anObject [

	constructorValuable := anObject
]
