Class {
	#name : 'AutometaConstructorDescription',
	#superclass : 'Object',
	#instVars : [
		'constructorArguments',
		'constructorValuable'
	],
	#category : 'Autometa-Model',
	#package : 'Autometa',
	#tag : 'Model'
}

{ #category : 'accessing' }
AutometaConstructorDescription >> constructorArguments [

	^ constructorArguments
]

{ #category : 'accessing' }
AutometaConstructorDescription >> constructorArguments: anObject [

	constructorArguments := anObject
]

{ #category : 'accessing' }
AutometaConstructorDescription >> constructorValuable [

	^ constructorValuable
]

{ #category : 'accessing' }
AutometaConstructorDescription >> constructorValuable: anObject [

	constructorValuable := anObject
]
