Class {
	#name : 'AutometaTestObjectNoDefinitionSubclassSublClass',
	#superclass : 'AutometaTestObjectNoDefinitionSubclass',
	#instVars : [
		'subClassSubclassSlot'
	],
	#category : 'Autometa-Tests',
	#package : 'Autometa',
	#tag : 'Tests'
}

{ #category : 'accessing' }
AutometaTestObjectNoDefinitionSubclassSublClass >> subClassSubclassSlot [

	^ subClassSubclassSlot
]

{ #category : 'accessing' }
AutometaTestObjectNoDefinitionSubclassSublClass >> subClassSubclassSlot: anObject [

	subClassSubclassSlot := anObject
]
