Class {
	#name : 'AutometaNoVerboseLevel',
	#superclass : 'Object',
	#category : 'Autometa-Model',
	#package : 'Autometa',
	#tag : 'Model'
}

{ #category : 'as yet unclassified' }
AutometaNoVerboseLevel >> endBuilding [
]

{ #category : 'as yet unclassified' }
AutometaNoVerboseLevel >> endClass: aClass [
]

{ #category : 'as yet unclassified' }
AutometaNoVerboseLevel >> startBuilding: aCollection [
]

{ #category : 'as yet unclassified' }
AutometaNoVerboseLevel >> startClass: aClass [
]
